const data = [
	{name: "Akechi Mitsuhide", mainStats: ["Atk %","Crit","FD"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Ares", mainStats: ["Spd","Def %","Hp %"], subStats:["Hp %","Def %","Tenacity","Crit DMG Reduction"]},
	{name: "Artemis ", mainStats: ["Spd","Hp %","Atk %"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Benkei", mainStats: ["Atk %","Crit","FD"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Columbus", mainStats: ["Crit","FD","Atk %"], subStats:["Crit","Atk %","FD","Hit"]},
	{name: "Copernicus ", mainStats: ["Spd","Def %","Hp %"], subStats:["Atk %","Hp %","Def %","Tenacity"]},
	{name: "Dante", mainStats: ["Spd","FD","Atk %"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Darwin", mainStats: ["Spd","Def %","Hp %"], subStats:["Hp %","Def %","Tenacity","Crit DMG Reduction"]},
	{name: "DaVinci", mainStats: ["Spd","FD","Atk %"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Hannibal", mainStats: ["Spd","Def %","Atk %"], subStats:["Atk %","Hp %","Def %","Tenacity"]},
	{name: "Helen", mainStats: ["Hp %","Crit DMG Reduction","Def %"], subStats:["Hp %","Def %","Crit DMG Reduction","Tenacity"]},
	{name: "Himiko", mainStats: ["Spd","Def %","Hp %"], subStats:["Hp %","Def %","Tenacity","Crit DMG Reduction"]},
	{name: "Honda Tadakatsu", mainStats: ["Def %","Tenacity","Hp %"], subStats:["Def %","Hp %","Tenacity","Crit DMG Reduction"]},
	{name: "Hua Tuo", mainStats: ["Atk %","Def %","Hp %"], subStats:["Atk %","Hp %","Def %","Tenacity"]},
	{name: "Huang Zhong", mainStats: ["Crit","Atk %","Crit DMG"], subStats:["Crit","Atk %","FD","Hit"]},
	{name: "Hugo", mainStats: ["Spd","Def %","Hp %"], subStats:["Hp %","Def %","Tenacity","Crit DMG Reduction"]},
	{name: "Izumo no Okuni", mainStats: ["Hp %","Def %","Atk %"], subStats:["Hp %","Atk %","Def %","Tenacity"]},
	{name: "Lancelot ", mainStats: ["Atk %","Crit","FD"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Loki", mainStats: ["Hp %","FD","Atk %"], subStats:["Hp %","Atk %","FD","Crit"]},
	{name: "Merlin", mainStats: ["Atk %","FD","Crit DMG"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Michelangelo", mainStats: ["Spd","Def %","Hp %"], subStats:["Hp %","Def %","Tenacity","Crit DMG Reduction"]},
	{name: "Minamoto no Yoshitsune", mainStats: ["Crit","FD","Atk %"], subStats:["Crit","Atk %","FD","Hit"]},
	{name: "Miyamoto Musashi", mainStats: ["Atk %","Crit DMG","FD"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Mochizuki Chiyome", mainStats: ["Atk %","Crit","FD"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Morgana", mainStats: ["Spd","Def %","Hp %"], subStats:["Hp %","Atk %","Def %","Tenacity"]},
	{name: "Mozart", mainStats: ["Hp %","Crit DMG Reduction","Def %"], subStats:["Hp %","Def %","Atk %","Crit DMG Reduction"]},
	{name: "Napoleon", mainStats: ["Atk %","Crit","FD"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Nene", mainStats: ["Spd","Def %","Hp %"], subStats:["Hp %","Def %","Tenacity","Crit DMG Reduction"]},
	{name: "Octavius", mainStats: ["Atk %","Crit","FD"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Oda Nobunaga", mainStats: ["Atk %","FD","Crit DMG"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Raphael", mainStats: ["Atk %","Hp %","FD"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Remus", mainStats: ["Spd","Def %","Hp %"], subStats:["Hp %","Def %","Tenacity","Crit DMG Reduction"]},
	{name: "Richard", mainStats: ["Atk %","NA","FD"], subStats:["Crit","Atk %","FD","Hit"]},
	{name: "Robin Hood", mainStats: ["Spd","Def %","Hp %"], subStats:["Hp %","Def %","Tenacity","Crit DMG Reduction"]},
	{name: "Romulus", mainStats: ["Hp %","Tenacity","Def %"], subStats:["Hp %","Def %","Tenacity","Crit DMG Reduction"]},
	{name: "Shakespeare", mainStats: ["Crit","Hp %","Def %"], subStats:["Crit","Def %","Hp %","Tenacity"]},
	{name: "Sima Yi", mainStats: ["Atk %","Crit","FD"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Taishi Ci", mainStats: ["Spd","NA","Atk %"], subStats:["Crit","Atk %","FD","Hit"]},
	{name: "Takenaka Shigeharu", mainStats: ["Spd","Def %","Atk %"], subStats:["Atk %","FD","Crit","Def %"]},
	{name: "Tamamo no Mae", mainStats: ["Spd","NA","Atk %"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Thor", mainStats: ["Atk %","Crit","FD"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Tokugawa Ieyasu", mainStats: ["Hp %","Def %","Atk %"], subStats:["Hp %","Atk %","Def %","Tenacity"]},
	{name: "Twins", mainStats: ["Spd","NA","Hp %"], subStats:["Hp %","Def %","Tenacity","Crit DMG Reduction"]},
	{name: "Xu Chu", mainStats: ["Spd","Def %","Hp %"], subStats:["Hp %","Def %","Tenacity","Crit DMG Reduction"]},
	{name: "Yagyu Jubei Mitsuyoshi", mainStats: ["Atk %","Crit","FD"], subStats:["Atk %","FD","Crit","Hit"]},
	{name: "Zhao Yun", mainStats: ["Hp %","Def %","Atk %"], subStats:["Hp %","Atk %","Def %","Tenacity"]},
	{name: "Zhen Ji", mainStats: ["Spd","Def %","Hp %"], subStats:["Hp %","Def %","Tenacity","Crit DMG Reduction"]}]